[package]
name = "rag_sqlite_vec"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
ndarray = "0.15"
ort = { version = "2.0.0-rc.10", features = ["ndarray"] }
rust_tokenizers = { version = "8.1.1" }
